### PR TITLE
Implement fix

### LINKED ISSUE #3: `addTopDecls` bug
@mpickering I saw https://ghc.haskell.otherg/trac/ghc/ticket/13587, so I converted the code in `implement-fix` to untyped template haskell and it fails with the same error.

### PR DESCRIPTION
**Pull request by LightAndLight**
Closes #3

### CODE REVIEW

File: src/CFG.hs [hunk 1]
```diff
@@ -409,26 +400,11 @@ go_staged supply context e = do
       unsafeTExpCoerce (context !! n)
 
     IR_Mu ty f
-      | s:supply' <- supply -> do
-        mkDecl supply context f-- go_staged supply' context (f t))
+      | s:supply' <- supply ->
+          [|| let x = $$(go_staged supply' (unTypeQ [|| x ||] : context) (f $ MkVar s)) in x ||]
```
Comment (mpickering) [inline src/CFG.hs]: Just as I imagined.

**Review by mpickering — APPROVED** [review]
